### ISSUE TITLE
Problem to install via Composer in Contao managed Edition

### ISSUE THREAD

**Issue by Clex1o1** [richardhj/contao-simple-ajax#4]
Hi, I'm using Contao 4.4.x managed edition and i can't install richardhj/contao-simple-ajax v1.2.1.
It requires contao/core 3.2.0 - 3.5.9.

**Comment by fritzmg** [comment]
> It requires contao/core 3.2.0 - 3.5.9.

It requires `"contao/core": "~3.2"` which means Contao `>=3.2,<4-dev` which means Contao 3.2.0 - 3.5.x (currently). As far as I can see this extension has not been released for Contao 4 yet.

But in Contao 4 it's easy to create your own routes anyway, so you don't really need this extension.

**Comment by Clex1o1** [comment]
okay, thank for your fast answer. I read the manual for symfony routes, but it does not work with the `routing.yml` file. I think it works different in the managed edition of contao 4. Do you know how i create my own route to the controller of my bundle?

**Comment by fritzmg** [comment]
Yes, you need to load your `routing.yml` via a ContaoManager Plugin. See https://github.com/inspiredminds/contao-facebook-login/blob/master/src/FacebookLoginBundle/ContaoManagerPlugin.php#L42-L51 for example.

**Comment by Clex1o1** [comment]
perfect, works thank you
