### ISSUE TITLE
Contao 4.* Compatibility

### ISSUE THREAD

**Issue by fkaminski** [richardhj/contao-simple-ajax#5]
Contao 4.x please ...

**Comment by richardhj** [comment]
> Contao 4.x please ...

Ok.

## If you want to support Contao 3 and Contao 4

Add this to your `composer.json`:
```
  "require": {
    "richardhj/contao-simple-ajax": "~1.2 || ~1.3"
  },
```

And pls provide a `Symfony\Component\HttpFoundation\Response` and do not use the hooks if avoidable.

## If you want to support Contao 4

Use the Symfony routes. Various documentation available, e.g. the Contao cookbook and the Symfony docs.

**Comment by fritzmg** [comment]
> `"richardhj/contao-simple-ajax": "~1.2 || ~1.3"`

Isn't that superfluous? `~1.2` already means `>=1.2.0,<2-dev`.

**Comment by richardhj** [comment]
Sure, you're right!
So updating to Contao 4 with simple-ajax should be as easy as pie now.
