### ISSUE TITLE
Error: container ist private

### ISSUE THREAD

**Issue by contaoacademy** [richardhj/contao-simple-ajax#8]
**Contao Version:**
4.6.8

**Error-Message:**
`Controller "richardhj.simple_ajax.controller" cannot be fetched from the container because it is private`

**My Workaround:**
I added `public: true` to the `richardhj.simple_ajax.controller:` in `service.yml`

**Comment by richardhj** [comment]
Please check the changes resulting of #7.

**Comment by contaoacademy** [comment]
Works great!
